a=input('digite algo:')
print('O tipo de variável primitivel é', type(a))
print ('Só tem espaço?',a.isspace())
print('É um número ?',a.isnumeric())
print('É alfabetico?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('Está em maiúsculo?',a.isupper())
print('Está em minúscula?',a.islower())
print('Está capitalizada?',a.istitle())